data class Post(
    var id: Long,
    val ownerId: Int,
    var fromId: Int,
    var createdBy: Int,
    val date: Int,
    var attachment: Array<Attachment>?,
//    val postSource: PostSource,
//    val geo: Geo,
//    val copyHistory: CopyHistory,
//    val text: String,
//    val replyOwnerId: Int,
//    val replyPostId: Int,
//    val friendOnly: Boolean,
//    val postType: String,
//    val signer: Int,
//    val canPin: Boolean,
//    val canDelete: Boolean,
//    val canEdit: Boolean,
//    val isPinned: Boolean,
//    val markedAsAdd: Boolean,
//    val isFavorite: Boolean,
//    val postponedId: Int,
//    val comments: Comments,
//    val copyright: Copyright,
//    val likes: Likes,
//    val repost: Repost,
//    val views: Views,
//    val donut: Donut
) {}
